name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install rustc and clippy nightly
      uses: dtolnay/rust-toolchain@stable
      with:
         toolchain: nightly-2025-06-13
         components: cargo, rustc, clippy, rustfmt
    - name: Install Just
      uses: taiki-e/install-action@v2
      with:
        tool: just
    - name: "Tests: Tokio-uring"
      run: RUST_LOG=debug RUST_BACKTRACE=1 just test-tokio-uring
      timeout-minutes: 10
    - name: "Tests: Monoio"
      run: RUST_LOG=debug RUST_BACKTRACE=1 just test-monoio
      timeout-minutes: 10
    - name: "Lint Checks: Tokio-uring"
      run: just lint-tokio-uring
      timeout-minutes: 5
    - name: "Lint Checks: Monoio"
      timeout-minutes: 5 
      run: just lint-monoio
    - name: "Formatting Checks"
      timeout-minutes: 5
      run: just check-formatting
