name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install rustc and clippy nightly
      uses: dtolnay/rust-toolchain@stable
      with:
         toolchain: nightly
         components: cargo, rustc, clippy, rustfmt
    - name: Install Just
      uses: taiki-e/install-action@v2
      with:
        tool: just
    - name: "Tests: Tokio-uring"
      run: just test-tokio-uring
    - name: "Tests: Monoio"
      run: just test-monoio
    - name: "Lint Checks: Tokio-uring"
      run: just lint-tokio-uring
    - name: "Lint Checks: Monoio"
      run: just lint-monoio
    - name: "Formatting Checks"
      run: cargo fmt --check
