name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install rustc and clippy nightly
      uses: dtolnay/rust-toolchain@stable
      with:
         toolchain: nightly
         components: cargo, rustc, clippy, rustfmt
    - name: "Lint Checks"
      run: cargo clippy 
